name: ink_dart
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  lint: ^1.3.0
  test: ^1.14.4
